# ==========================================
# KHAI BÁO BỘ ĐẾM CHỐNG DOS (Cho phép tối đa 5 request/giây trên 1 IP)
# ==========================================
limit_req_zone $binary_remote_addr zone=dos_defense:10m rate=5r/s;

upstream frontend_upstream {
    server frontend:80;
}

upstream backend_upstream {
    server backend:5000;
}

server {
    listen 80;
    server_name _;

    client_max_body_size 10M;

    # Ghi log để Promtail (Phase 3) có thể scrape
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    # GZIP
    gzip on;
    gzip_types text/plain text/css application/json application/javascript image/svg+xml;
    gzip_min_length 1024;

    limit_req zone=dos_defense burst=50 nodelay;

    # =========================
    # API → backend
    # =========================
    location /api/ {
        proxy_pass         http://backend_upstream;
        proxy_http_version 1.1;

        include /etc/nginx/proxy_headers.conf; # Tập hợp các header cần thiết cho proxy

        proxy_read_timeout 120s;
        proxy_connect_timeout 120s;
        proxy_send_timeout 120s;
    }

# =========================
    # Uploads → Phục vụ file tĩnh (Chuẩn Production)
    # =========================
    location ^~ /uploads/ {
        # 1. Trỏ vào thư mục gốc chứa thư mục uploads
        root /app; 

        # 2. Bắt buộc load các định dạng file (để trả về image/png thay vì text/html)
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        # 3. Cache ảnh ở trình duyệt 30 ngày cho nhẹ server
        expires 30d;
        add_header Cache-Control "public, immutable";
        
        # 4. Nếu file không tồn tại, văng lỗi 404 luôn, không ném về React
        try_files $uri =404; 
    }

    # =========================
    # STATIC FILES & SPA → frontend
    # =========================
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico)$ {
        proxy_pass http://frontend_upstream;

        include /etc/nginx/proxy_headers.conf; # Tập hợp các header cần thiết cho proxy
        include /etc/nginx/security_headers.conf; # Thêm header bảo mật cho static assets

        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        proxy_pass http://frontend_upstream;

        include /etc/nginx/proxy_headers.conf; # Tập hợp các header cần thiết cho proxy
        include /etc/nginx/security_headers.conf; # Thêm header bảo mật cho static assets

        add_header Cache-Control "no-store";
    }
}